# Generated by Django 5.0.4 on 2024-05-08 15:26

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(default=None, on_delete=models.CASCADE, to='polls.Question'),
            preserve_default=False,
        ),
    ]

